server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
  port: 8443
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT : true
    deserialization:
      ACCEPT_FLOAT_AS_INT : false
logging:
    level:
        org: 
           hibernate:
              SQL: DEBUG
              type:
                  descriptor:
                      sql: 
                         BasicBinder: trace     
##TODO implement swagger
